//
//  GooglePlaceType.swift
//  TodoMap
//
//  Created by Suguru on 8/21/23.
//

import Foundation

enum GooglePlaceType: String {
    case accounting = "accounting"
    case airport = "airport"
    case amusementPark = "amusement_park"
    case aquarium = "aquarium"
    case artGallery = "art_gallery"
    case atm = "atm"
    case bakery = "bakery"
    case bank = "bank"
    case bar = "bar"
    case beautySalon = "beauty_salon"
    case bicycleStore = "bicycle_store"
    case bookStore = "book_store"
    case bowlingAlley = "bowling_alley"
    case busStation = "bus_station"
    case cafe = "cafe"
    case campground = "campground"
    case carDealer = "car_dealer"
    case carRental = "car_rental"
    case carRepair = "car_repair"
    case carWash = "car_wash"
    case casino = "casino"
    case cemetery = "cemetery"
    case church = "church"
    case cityHall = "city_hall"
    case clothingStore = "clothing_store"
    case convenienceStore = "convenience_store"
    case courthouse = "courthouse"
    case dentist = "dentist"
    case departmentStore = "department_store"
    case doctor = "doctor"
    case drugstore = "drugstore"
    case electrician = "electrician"
    case electronicsStore = "electronics_store"
    case embassy = "embassy"
    case fireStation = "fire_station"
    case florist = "florist"
    case funeralHome = "funeral_home"
    case furnitureStore = "furniture_store"
    case gasStation = "gas_station"
    case gym = "gym"
    case hairCare = "hair_care"
    case hardwareStore = "hardware_store"
    case hinduTemple = "hindu_temple"
    case homeGoodsStore = "home_goods_store"
    case hospital = "hospital"
    case insuranceAgency = "insurance_agency"
    case jewelryStore = "jewelry_store"
    case laundry = "laundry"
    case lawyer = "lawyer"
    case library = "library"
    case lightRailStation = "light_rail_station"
    case liquorStore = "liquor_store"
    case localGovernmentOffice = "local_government_office"
    case locksmith = "locksmith"
    case lodging = "lodging"
    case mealDelivery = "meal_delivery"
    case mealTakeaway = "meal_takeaway"
    case mosque = "mosque"
    case movieRental = "movie_rental"
    case movieTheater = "movie_theater"
    case movingCompany = "moving_company"
    case museum = "museum"
    case nightClub = "night_club"
    case painter = "painter"
    case park = "park"
    case parking = "parking"
    case petStore = "pet_store"
    case pharmacy = "pharmacy"
    case physiotherapist = "physiotherapist"
    case plumber = "plumber"
    case police = "police"
    case postOffice = "post_office"
    case primarySchool = "primary_school"
    case realEstateAgency = "real_estate_agency"
    case restaurant = "restaurant"
    case roofingContractor = "roofing_contractor"
    case rvPark = "rv_park"
    case school = "school"
    case secondarySchool = "secondary_school"
    case shoeStore = "shoe_store"
    case shoppingMall = "shopping_mall"
    case spa = "spa"
    case stadium = "stadium"
    case storage = "storage"
    case store = "store"
    case subwayStation = "subway_station"
    case supermarket = "supermarket"
    case synagogue = "synagogue"
    case taxiStand = "taxi_stand"
    case touristAttraction = "tourist_attraction"
    case trainStation = "train_station"
    case transitStation = "transit_station"
    case travelAgency = "travel_agency"
    case university = "university"
    case veterinaryCare = "veterinary_care"
    case zoo = "zoo"
}
